### ISSUE TITLE
valleys  ?

### ISSUE THREAD

**Issue by tech-a-go-go** [bbc/slayer#10]
Hi there,

Can this library detect valleys as well ?

Cheers

**Comment by thom4parisot** [comment]
Hi @tech-a-go-go,

by default the library is focused on detecting peaks only.
There is an undocumented method `.use()` to which you can pass a detection function.

You can see it in use here:

https://github.com/bbc/slayer/blob/4b0cdc5080f46f5940c89c081dbad16e2be4e021/lib/core.js#L32

And the default peak calculation function:

https://github.com/bbc/slayer/blob/4b0cdc5080f46f5940c89c081dbad16e2be4e021/lib/algorithms/default.js#L16-L22

You would have 1) to replace `arrayMax` with a function to the lowest value of an array as well as 2) to change the comparison statement (last line).

**Comment by tech-a-go-go** [comment]
HI @oncletom,

Thanks for your reply.
That helps me a lot !

Let me share one thing I've noticed by reading this code, [https://github.com/bbc/slayer/blob/master/lib/utils.js](url)
```
arrayMax: function arrayMax(array){
    return Math.max.apply(null, array);
},
```

Math.max.apply treats a null value as 0 so if the array is like [null, -40, -20, -10, -20, -50], the method returns 0 as a max value ( -10 is expected as max though ).
So before using Math.max.apply method, null values must be removed from the array.
(If this library doesn't support negative values, plz forget about it.) 

Cheers

**Comment by thom4parisot** [comment]
@tech-a-go-go ah, good catch! `array.filter()` should do the job.

Although in your case you might want to have an `arrayMin` version if you want to pick the valley values :-)
